from deepClassifier.components.data_ingestion import DataIngestion
from deepClassifier.components.prepare_base_model import PrepareBaseModel
from deepClassifier.components.call_back import PrepareCallback
from deepClassifier.components.training import Training