from deepClassifier.entity.config_entity import DataIngestionConfig
from deepClassifier.entity.config_entity import PrepareBaseModelConfig
from deepClassifier.entity.config_entity import PrepareCallbacksConfig
from deepClassifier.entity.config_entity import TrainingConfig