
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source: face-mask-detection.zip
  local_data_file: artifacts/data_ingestion/face-mask-detection.zip
  unzip_dir: artifacts/data_ingestion
