
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source: face-mask-detection.zip
  local_data_file: artifacts/data_ingestion/face-mask-detection.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5